# i3blocks configuration file
#
# The i3blocks man page describes the usage of the binary,
# and its website describes the configuration:
#
#     https://vivien.github.io/i3blocks


# Global properties
separator=true
separator_block_width=15

[spotify]
label= 
command=/home/$USER/.config/i3/scripts/spotify.py
color=#81b71a
interval=5

#[volume]
#command=/home/$USER/.config/i3/scripts/volume
#LABEL=♪
#interval=1

[flameshot]
command=/home/$USER/.config/i3/scripts/flameshot.sh
interval=once
signal=1

[bandwidth3]
command=/home/$USER/.config/i3/scripts/git/i3blocks-contrib/bandwidth3/bandwidth3
interval=persist
markup=pango
#LABEL=<span font='FontAwesome'>  </span>
#IFACE=[automatically determined]
#DT=3
#UNIT=Mb
# Exposed variables: rx, wx, tx, unit, iface
#PRINTF_COMMAND=printf "${LABEL}%-5.1f/%5.1f %s/s\n", rx, wx, unit;

[iface]
command=/home/$USER/.config/i3/scripts/git/i3blocks-contrib/iface/iface
#LABEL=wlan0:
#IFACE=wlan0
#ADDRESS_FAMILY=inet6?
color=#00FF00
interval=10
# set this to 1 to display the name of the connected WIFI interface instead of the IP address.
display_wifi_name=0

[cpu_usage]
command=/home/$USER/.config/i3/scripts/git/i3blocks-contrib/cpu_usage/cpu_usage
interval=10
LABEL=CPU 
#min_width=CPU: 100.00%
#T_WARN=50
#T_CRIT=80
#DECIMALS=2
#COLOR_NORMAL=#EBDBB2
#COLOR_WARN=#FFFC00
#COLOR_CRIT=#FF0000

[memory]
command=/home/$USER/.config/i3/scripts/memory
label= 
interval=30

[disk]
command=/home/$USER/.config/i3/scripts/disk
LABEL= 
#DIR=$HOME
#ALERT_LOW=10
interval=30

[battery2]
command=/home/$USER/.config/i3/scripts/battery2
markup=pango
interval=30

[time]
label= 
command=date '+%Y-%m-%d %H:%M:%S'
interval=1

[arch-update]
command=/home/$USER/.config/i3/scripts/git/i3blocks-contrib/arch-update/arch-update 
interval=3600
markup=pango
LABEL=Updates: 
